# Generated by Django 2.0.2 on 2018-03-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('kunden_id', models.AutoField(primary_key=True, serialize=False)),
                ('prename', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('bakeryName', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('plz', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=100)),
                ('einheit', models.PositiveIntegerField()),
                ('pricePerUnit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rechnungsDatum', models.DateField()),
                ('bezahlStatus', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestellDatum', models.DateTimeField(verbose_name='date published')),
                ('kunde', models.ForeignKey(on_delete=False, to='portal.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menge', models.IntegerField()),
                ('asTeig', models.BooleanField()),
                ('bestellung', models.ForeignKey(on_delete=True, to='portal.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezeptBez', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=False, to='portal.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=False, to='portal.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='zutat',
            field=models.ManyToManyField(through='portal.RecipeList', to='portal.Ingredient'),
        ),
        migrations.AddField(
            model_name='orderposition',
            name='rezept',
            field=models.ForeignKey(on_delete=True, to='portal.Recipe'),
        ),
        migrations.AddField(
            model_name='order',
            name='rezepte',
            field=models.ManyToManyField(through='portal.OrderPosition', to='portal.Recipe'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=False, to='portal.Order'),
        ),
    ]
