# Generated by Django 2.0.2 on 2018-03-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newattribute',
            field=models.CharField(default='test', max_length=4),
        ),
    ]
