# Generated by Django 2.0.3 on 2018-03-20 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='benutzer',
            field=models.ForeignKey(default=0, on_delete=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
