# Generated by Django 2.0.2 on 2018-03-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='einheit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'ml'), ('mg', 'mg'), ('s', 'Stück'), ('p', 'Prise'), ('l', 'Liter')], help_text='Einheit', max_length=2),
        ),
    ]
