# Generated by Django 2.0.2 on 2018-03-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20180315_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('g', 'Gramm'), ('mg', 'Milligramm'), ('s', 'Stück'), ('p', 'Prise')], help_text='Einheit', max_length=2),
        ),
    ]
