# Generated by Django 2.0.2 on 2018-03-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_customer_newattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='newattribute',
        ),
    ]
