# Generated by Django 2.0.2 on 2018-03-15 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_customer_newattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bakeryName',
            new_name='bakery_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredientName',
            new_name='ingredient_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='pricePerUnit',
            new_name='price_per_unit',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='bezahlStatus',
            new_name='bezahl_status',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='rechnungsDatum',
            new_name='rechnungs_datum',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bestellDatum',
            new_name='bestell_datum',
        ),
        migrations.RenameField(
            model_name='orderposition',
            old_name='asTeig',
            new_name='als_teig',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='rezeptBez',
            new_name='rezept_bezeichnung',
        ),
    ]
