# Generated by Django 2.0.2 on 2018-03-15 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0005_auto_20180315_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kunde',
            field=models.ForeignKey(default=False, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
