# Generated by Django 2.0.2 on 2018-03-15 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_order_kunde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='kunde',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
