# Generated by Django 2.0.2 on 2018-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20180315_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('ml', 'Milliliter'), ('l', 'Liter'), ('g', 'Gramm'), ('mg', 'Milligramm'), ('Stück', 'Stück'), ('Prise/n', 'Prise/n (3g)')], help_text='Einheit', max_length=6),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='bezahlStatus',
            field=models.CharField(choices=[('offen', 'offen'), ('aufgeschoben', 'aufgeschoben'), ('bezahlt', 'bezahlt'), ('unbekannt', 'bitte Rechnung prüfen')], default='bitte Rechnung prüfen', help_text='Status des Bezahlvorgangs', max_length=12),
        ),
    ]
