# Generated by Django 2.0.2 on 2018-03-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20180315_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bezahlStatus',
            field=models.CharField(blank=True, choices=[('offen', 'offen'), ('aufgeschoben', 'aufgeschoben'), ('bezahlt', 'bezahlt'), ('bitte Rechnung prüfen', 'bitte Rechnung prüfen')], default='bitte Rechnung prüfen', help_text='Status des Bezahlvorgangs', max_length=21),
        ),
    ]
