# Generated by Django 2.0.2 on 2018-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20180315_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bezahlStatus',
            field=models.CharField(choices=[('offen', 'offen'), ('aufgeschoben', 'aufgeschoben'), ('bezahlt', 'bezahlt'), ('unbekannt', 'bitte Rechnung prüfen')], default='bitte Rechnung prüfen', help_text='Status des Bezahlvorgangs', max_length=12),
        ),
    ]
